domain: default
descriptors:
  - key: org
    value: carbon.super
    descriptors:
      - key: vhost
        value: localhost
        descriptors:
          - key: path
            value: /v2/ratelimitService
            descriptors:
              - key: method
                value: ALL
                rate_limit:
                  unit: minute
                  requests_per_unit: 5
          - key: path
            value: /v2/operationLevelRL/pet/findByStatus
            descriptors:
              - key: method
                value: GET
                rate_limit:
                  unit: minute
                  requests_per_unit: 3
          - key: path
            value: /v2/operationLevelRL/pet/{petId}
            descriptors:
              - key: method
                value: GET
                rate_limit:
                  unit: minute
                  requests_per_unit: 5
