# Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: '2.0'
info:
  version: 'v1'
  title: Choreo-Connect Interceptor Service
  description: Interceptor Service
  contact:
    name: WSO2
    url: http://wso2.com/products/api-manager/
host: interceptor-service:8443
basePath: /api/v1
securityDefinitions: {}
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /handle-request:
    post:
      description: Handle Request
      summary: handleRequest
      tags:
      - Request
      operationId: handleRequest
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: false
        enum:
        - application/json
        type: string
        description: ''
      - name: body
        in: body
        required: false
        description: Content of the request
        schema:
          $ref: '#/definitions/RequestbodyofRequesthandler'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ResponsebodyofRequesthandler'
          headers: {}
  /handle-response:
    post:
      description: Handle Response
      summary: handleResponse
      tags:
      - Response
      operationId: handleResponse
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: false
        enum:
        - application/json
        type: string
        description: ''
      - name: body
        in: body
        required: false
        description: Content of the request
        schema:
          $ref: '#/definitions/RequestbodyofResponsehandler'
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/ResponseBody'
          headers: {}
definitions:
  RequestbodyofRequesthandler:
    title: RequestbodyofRequesthandler
    type: object
    properties:
      requestHeaders:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      requestTrailers:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      requestBody:
        description: Base64 encoded body
        example: PGhlbGxvPndvcmxkPC9oZWxsbz4K
        type: string
      invocationContext:
        $ref: '#/definitions/Invocationcontext'
  ResponsebodyofRequesthandler:
    title: ResponsebodyofRequesthandler
    type: object
    properties:
      directRespond:
        example: false
        type: boolean
      responseCode:
        example: 200
        type: integer
        format: int32
      dynamicEndpoint:
        $ref: '#/definitions/Dynamicendpoint'
      headersToAdd:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      headersToReplace:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      headersToRemove:
        description: Array of header keys
        example:
        - key1
        - key2
        type: array
        items:
          type: string
      trailersToAdd:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      trailersToReplace:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      trailersToRemove:
        description: Array of header keys
        example:
        - key1
        - key2
        type: array
        items:
          type: string
      body:
        description: Base64 encoded body
        example: PGhlbGxvPndvcmxkPC9oZWxsbz4K
        type: string
      interceptorContext:
        description: Map (string-to-string dictionary) of key value pairs
        example:
          key1: value1
          key2: value2
        type: object
        additionalProperties:
          type: string
  RequestbodyofResponsehandler:
    title: RequestbodyofResponsehandler
    type: object
    properties:
      responseCode:
        example: 200
        type: integer
        format: int32
      requestHeaders:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      requestTrailers:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      requestBody:
        description: Base64 encoded body
        example: PGhlbGxvPndvcmxkPC9oZWxsbz4K
        type: string
      responseHeaders:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      responseTrailers:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      responseBody:
        description: Base64 encoded body
        example: PGhlbGxvPndvcmxkPC9oZWxsbz4K
        type: string
      invocationContext:
        $ref: '#/definitions/Invocationcontext'
      interceptorContext:
        description: Map (string-to-string dictionary) of key value pairs
        example:
          key1: value1
          key2: value2
        type: object
        additionalProperties:
          type: string
    required:
    - responseCode
  ResponseBody:
    title: ResponseBody
    type: object
    properties:
      responseCode:
        example: 200
        type: integer
        format: int32
      headersToAdd:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      headersToReplace:
        description: Map (string-to-string dictionary) of key value pairs of headers
        example:
          content-type: application/xml
          content-length: '40'
        type: object
        additionalProperties:
          type: string
      headersToRemove:
        description: Array of header keys
        example:
        - key1
        - key2
        type: array
        items:
          type: string
      trailersToAdd:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      trailersToReplace:
        description: Map (string-to-string dictionary) of key value pairs of trailers
        example:
          trailer1-key: value
        type: object
        additionalProperties:
          type: string
      trailersToRemove:
        description: Array of header keys
        example:
        - key1
        - key2
        type: array
        items:
          type: string
      body:
        description: Base64 encoded body
        example: PGhlbGxvPndvcmxkPC9oZWxsbz4K
        type: string
  Invocationcontext:
    title: Invocationcontext
    type: object
    properties:
      requestId:
        example: 75269e44-f797-4432-9906-cf39e68d6ab8
        type: string
      protocol:
        example: HTTP/1.1
        type: string
      scheme:
        example: https
        type: string
      apiName:
        example: PetStore
        type: string
      apiVersion:
        example: v1.0.0
        type: string
      vhost:
        example: localhost
        type: string
      supportedMethods:
        example: GET POST
        type: string
      method:
        example: POST
        type: string
      basePath:
        example: /petstore
        type: string
      path:
        example: /petstore/pet/1
        type: string
      pathTemplate:
        example: /pet/{petID}
        type: string
      source:
        example: 192.168.8.332:8080
        type: string
      prodClusterName:
        example: carbon.super_clusterProd_localhost_Online-Storev1.0.0
        type: string
      sandClusterName:
        type: string
      authenticationContext:
        $ref: '#/definitions/AuthenticationContext'
  Dynamicendpoint:
    title: Dynamicendpoint
    type: object
    properties:
      endpointName:
        example: my-dynamic-endpoint
        type: string
  AuthenticationContext:
    title: AuthenticationContext
    type: object
    properties:
      tokenType:
        example: JWT
        type: string
      token:
        example: xxxxxx-xxxx-xxxxxx-xxxx
        type: string
      keyType:
        example: PRODUCTION
        type: string
tags:
- name: interceptor
  description: Interceptor
- name: Request
  description: ''
- name: Response
  description: ''
