---
openapi: 3.0.0
servers:
  - url: http://petstore.swagger.io/v2
info:
  description: 'This is an example to demonstrate how to define endpoint references using  x-wso2-endpoints extension.'
  version: 1.0.0
  title: SwaggerPetStore
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: pet
    description: About your Pets
x-wso2-endpoints:                                             # defines x-wso2-endpoints
  - myEndpoint:
      urls:
        - https://petstore.swagger.io/v2
        - https://petstore.swagger.io/v5
      securityConfig:
        type: basic
        username: roshan
  - myEndpoint3:
      urls:
        - https://petstore.swagger.io/v3
        - https://petstore.swagger.io/v4
      securityConfig:
        type: basic
        username: rajith
x-wso2-basePath: /petstore/v1
x-wso2-production-endpoints: "#/x-wso2-endpoints/myEndpoint"  # refers to the x-wso2-endpoints defined above
paths:
  "/pet/findByStatus":
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      x-wso2-production-endpoints: "#/x-wso2-endpoints/myEndpoint3" # refers to the x-wso2-endpoints defined above
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              enum:
                - available
              default: available
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Pet"
        '400':
          description: Invalid status value
components:
  schemas:
    Pet:
      type: object
      required:
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        category:
          type: string
        name:
          type: string
        photoUrls:
          type: string
        status:
          type: string
      xml:
        name: Pet
  requestBodies:
    Pet:
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Pet"
        application/xml:
          schema:
            "$ref": "#/components/schemas/Pet"
      description: Pet object that needs to be added to the store
      required: true
