---
openapi: 3.0.0
info:
  description: API Definition for http2 backend
  title: http2 secured backend
  version: v1
paths:
  /hello:
    get:
      responses:
        "200":
          description: successful operation
x-wso2-basePath: /http2_secured
x-wso2-http2-backend-enabled: true
x-wso2-production-endpoints:
  urls:
    - https://mockBackend:2351